---

- name: Ensure firewalld is installed
  ansible.builtin.package:
    name: firewalld

- name: Allow all internal communication (IPv4)
  when: opencast_firewall_ipv4
  ansible.builtin.firewalld:
    source: "{{ lookup('community.general.dig', item) }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  loop: '{{ opencast_firewall_internal_hosts }}'

- name: Allow all internal communication (IPv6)
  when: opencast_firewall_ipv6
  ansible.builtin.firewalld:
    source: "{{ lookup('community.general.dig', item, 'qtype=AAAA') }}"
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  loop: '{{ opencast_firewall_internal_hosts }}'

- name: Allow https
  when: inventory_hostname in opencast_firewall_http_hosts
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http
    - https
