---
name: ansible lint

on:  # noqa yaml
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: pip3 install ansible ansible-lint yamllint

      - run: yamllint --strict -c .yamllint .

      - run: ansible-lint
